version: '3'
services:
  db:
    container_name: db
    image: liontechacademy/bankingapps:bankingappdb.v1
    ports:
      - 5001:3306
    volumes:
      - bank:/var/lib/mysql
    networks:
      - bank
  app:
    container_name: app
    image: liontechacademy/bankingapps:bankingapp.v1
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - bank
volumes:
  bank:
networks:
  bank:
    driver: bridge
