---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: bankingapp
  name: bankingapp-social
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: bankingapp
    spec:
      containers:
      - image:  liontechacademy/bankingapps:bankingappdb.v1
        name: bankingapp
        ports:
        - name: bankingapp
          containerPort: 3306
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: bankingapp
  name: bankingapp
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 5001
  selector:
    name: bankingapp


################################################ DB DEPLOYMENT. 

